### ISSUE TITLE
Client error: `GET https://www.endomondo.com/users/123456` resulted in a `403 Forbidden`

### ISSUE THREAD

**Issue by jsalatiel** [fabulator/endomondo-api#5]
Hi, I have an php script that just converts cycling workouts to Weight workouts. It worked fine for several years, but a few months ago it stopped working with the following errors:

```
2 workouts found!
Workout "Cycling, sport" was 33min long. It started at 13.08.2019 05:49:20 -03:00 and end 13.08.2019 06:21:54 -03:00.( typeID = 2 )
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.endomondo.com/users/xxxxxxxx` resulted in a `403 Forbidden` response in /data/extras/endomondo/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /data/extras/endomondo/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /data/extras/endomondo/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /data/extras/endomondo/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /data/extras/endomondo/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /data/extras/endomondo/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /data/extras/endomond in /data/extras/endomondo/vendor/fabulator/endomondo-api/lib/Fabulator/Endomondo/EndomondoApi.php on line 41
```

I can not understand why it is throwing an unauthorized exception to edit  if it was able to retrieve the workout just fine.

This is the snippet of  the  script
```
$from = new \DateTime('today midnight');
$response = $endomondo->getWorkoutsFrom($from);

if  ($response['total']  > 0) {
	echo  $response['total'] . " workouts found!\n" ;
	foreach (array_reverse($response['workouts']) as $workout) {
 		echo $workout->toString() . "( typeID = " . $workout->getTypeId(). " )" . PHP_EOL;
		$currentType = $workout->getTypeName();
		if ($workout->getTypeId() == 0 ) {
			$workout->setTypeId(88);
			$newType = $workout->getTypeName();
			$workout->setDistance(0);
			$endomondo->editWorkout($workout);
			echo "Type set from " . $currentType . " to " . $newType;
		} elseif($workout->getTypeId() == 2 ) {
			$workout->setTypeId(46);
			$workout->setTitle("Weight");
			$workout->setDistance(0);
			$newType = $workout->getTypeName();
			$endomondo->editWorkout($workout);
			echo "Type set from " . $currentType . " to " . $newType;
		}
		echo PHP_EOL;
	}
}
?>
```

Any ideas ?

**Comment by fabulator** [comment]
Hello,
I'm sorry I no longer support PHP version of project. If I would have some ideas I would shared them with you but I don't have a clue. I'm using java/typescript version right know which is working fine for me. https://github.com/fabulator/endomondo-api-handler
